### ISSUE TITLE
Freeze when download

### ISSUE THREAD

**Issue by tt-thoma** [zenith391/OCEmu#11]
Yep, another.
When I download a file with OCEmu (using wget), it freeze.
Can you regulate the internet - display flow pls

**Comment by zenith391** [comment]
If you mean that it freezes temporarily, then it is normal and is due to the way OCEmu is designed.

**Comment by tt-thoma** [comment]
Can you just reverse the display-wget process ?

**Comment by tt-thoma** [comment]
Ok in config.cfg I disabled fast mode and it work normally
