### ISSUE TITLE
Use custom resolution

### ISSUE THREAD

**Issue by tt-thoma** [zenith391/OCEmu#12]
Can we use a custom resolution ?
If not, pls add it

**Comment by zenith391** [comment]
To change the resolution, OpenOS features a `resolution <width> <height>`, note that the resolution is in number of characters. The command is limited by the maximum resolution which can be changed in your `ocemu.cfg`.

For example let's you have a `ocemu.cfg` like that:
```
components {
  {"gpu", "9ba383c4-51d9-4b1a-bfd6-1fc466922e12", 0, 160, 50, 3},
  {"screen_sdl2", "0df59abc-4a59-4b97-b037-d370a15bcd0b", -1, 160, 50, 3},
  ...
}
```
160 and 50 are the maximum width and height (in number of characters) respectively.
If you want to change it, beware that the default maximum resolution, 160x50, is also the maximum resolution of tier 3 (max tier) computers in OpenComputers. So if you change the maximum resolution to something higher, some programs might break. To change the maximum resolution just change **both** numbers:
```
components {
  {"gpu", "9ba383c4-51d9-4b1a-bfd6-1fc466922e12", 0, 320, 100, 3},
  {"screen_sdl2", "0df59abc-4a59-4b97-b037-d370a15bcd0b", -1, 320, 100, 3},
  ...
}
```

**Comment by tt-thoma** [comment]
Ok thank you

**Comment by tt-thoma** [comment]
Also the default resolution (for me) was 80 25
