### ISSUE TITLE
Gpu/Screen Settings?

### ISSUE THREAD

**Issue by PublicVoidUpdate** [zenith391/OCEmu#20]
Is there an ability to change the tier of the GPU / screen in the emulator, I'm trying to run mineos but the resolution is too low on the emulated screen.

**Comment by zenith391** [comment]
Look for a file named `ocemu.cfg` in `%APPDATA%\\OCEmu` on Windows and `$XDG_CONFIG_HOME/ocemu` or `$HOME/.config/ocemu` on Linux.
Inside, you should see something like this:
```lua
    components {
      {"gpu", "9ba383c4-51d9-4b1a-bfd6-1fc466922e12", 0, 160, 50, 3},
      {"modem", "1342a5de-7657-41ee-b4c5-af176020a7fc", 1, false},
      {"eeprom", "c32ac015-0471-4200-914f-c4ade1f2c0f5", 9, "lua/bios.lua"},
      {"filesystem", "77ce427c-4072-4787-b040-35a333f69869", -1, "tmpfs", "tmpfs", false, 5},
      {"filesystem", "5c6c151a-59af-4a0b-be4f-1d639c2b9014", 5, nil, "OpenOS", false, 4, 4096000},
      {"internet", "fad3903a-450c-4c07-93f8-aa81ef43eb4b", 2},
      {"computer", "b0006609-b010-41aa-9732-0dfc5d9e1157", -1},
      {"ocemu", "71a192b7-ae54-4bfc-9369-7e3cad69875d", -1},
      {"screen_sdl2", "0df59abc-4a59-4b97-b037-d370a15bcd0b", -1, 160, 50, 3},
      {"keyboard_sdl2", "49342548-b0ea-4a5e-af02-6a2d6ecd107b", -1}
    }
```
In both the `"gpu"` and `"screen"` the last three values are respectively the resolution width, the resolution height and the tier. Just be sure in your configuration file that those last values are `160, 50, 3` (max resolution and max tier).

**Comment by PublicVoidUpdate** [comment]
Thank you so much!
