### ISSUE TITLE
Lua 5.3 on Windows

### ISSUE THREAD

**Issue by PublicVoidUpdate** [zenith391/OCEmu#21]
How do you use Lua 5.3 on the precompiled windows? i didn't see anything in the config file.

**Comment by Ocawesome101** [comment]
The precompiled binaries are very out of date.  In theory you could replace some DLLs and get Lua 5.3 support, but I have not tried this.

I am currently messing with getting an up-to-date Lua 5.2 build, and may mess with Lua 5.3 later.

**Comment by PublicVoidUpdate** [comment]
Ah, alright

**Comment by 2xddev** [comment]
I think there's new binaries now, they might have support for 5.3

**Comment by zenith391** [comment]
Yea, in theory the new binaries support Lua 5.3
I just need someone using Windows to test it before closing the issue

**Comment by Ocawesome101** [comment]
Have tested and confiremed lua 5.3 support, issue can be closed.
