### ISSUE TITLE
shutdown weirdness

### ISSUE THREAD

**Issue by Ocawesome101** [zenith391/OCEmu#24]
Something in ULOS's (admittedly complex) shutdown mechanisms distinctly does not like OCEmu.  When I run `poweroff` or `reboot`, precisely nothing happens most of the time - though I do get a `[ WAIT ] Stopping services` message the first time I run it.  In both OCVM and OpenComputers, this works fine.  I suspect it's got something to do with the fact that ULOS' shutdown routine calls `coroutine.yield` / `computer.pullSignal` in muptiple places.

**Comment by zenith391** [comment]
Out of all the bugs you have reported today, this is the only one I couldn't reproduce. It would be nice to tell me if you used the pre-built binaries or built from source OCEmu. If you built from source, could you also tell me from what commit was it?

**Comment by Ocawesome101** [comment]
I'm running OCEmu from source on the latest commit.  I retested after the changes you made earlier and the bug is still present on `f909517`.

Does running `poweroff` under ULOS work for you?

**Comment by zenith391** [comment]
Yes, running `poweroff` works for me. Do you use Lua 5.2 or Lua 5.3 to run OCEmu (idk, might be the problem) ? And give more information if possible please.

**Comment by Ocawesome101** [comment]
Odd.  I’m using Lua 5.3 since ULOS requires it, and I’m afraid I have
little more insight than you on this issue.

**Comment by Ocawesome101** [comment]
This was a ULOS bug, not an OCEmu one, and I've since fixed it.  Closing.
