### ISSUE TITLE
msys2 doesnt support your script apparently 

### ISSUE THREAD

**Issue by ghost** [zenith391/OCEmu#3]
![image](https://user-images.githubusercontent.com/37553921/98482926-06af1e80-21b1-11eb-97e5-8d47430a7486.png)

**Comment by zenith391** [comment]
I'm sorry but i didn't made (nor even use) `msys2_setup_ocemu.sh` but from the error message it suggests to use `MinGW-w64 Win Shell`

**Comment by misiuji** [comment]
It should work within the  `MinGW-w64 Win Shell` It's in the same folder as the msys2 shell. If you encounter any problems please open an issue.
