### ISSUE TITLE
gpu.bitblt extremely slow

### ISSUE THREAD

**Issue by Xandaros** [zenith391/OCEmu#36]
I just noticed that, in OCEmu, the bitblt operation is actually very slow and CPU intensive. I had a quick look at the code, but couldn't really figure out why this is.

I made a simple test script:
```lua
local component = require("component")
local gpu = component.gpu
local event = require("event")

local buffer = gpu.allocateBuffer()
gpu.setActiveBuffer(buffer)
local i = 1
while event.pull("key_down") do
    gpu.set(1, 1, tostring(i))
    gpu.bitblt()
    i = i + 1
end
```

Running this in OCEmu and typing keys will cause noticeable delay between key presses and the number counting up. In fact, it sometimes keeps going for multiple seconds after I stopped typing - depending on how much I typed.
In contrast, in-game this is almost instant with no noticeable delay whatsoever.

This is definitely related to the size of the buffer. If I do the same, but with the buffer height set to 1, it is MUCH faster.

I normally use a screen 100x as big as the normal T3 screen (800x250), but even with the 80x25 screen the emulator is much slower than the game.

If you want a less contrived example, I discovered this while working on my vim clone: https://github.com/Xandaros/yaocvim
Without setting `gpu.bitblt` to none (emulating an older OC version), it is basically unusable in the emulator. In game, on the other hand, using bitblt improves performance drastically.

This is not a particularly important issue for me, since I can just turn off the bitblt functionality while developing, but I thought I'd at least make a ticket so you are aware.

**Comment by zenith391** [comment]
`bitblt()` is in fact slow in OCEmu and that's an on going issue. However it should only have a significant impact when bitblting a dirty buffer (a buffer that you just modified using gpu.set or other functions)
In all case, I already have ideas on how to improve the performance so it should be done soon.
