### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by nazarii-muliak** [zenith391/OCEmu#43]
Hey guys, the link to Windows bootable distribution is not working anymore, can you fix it?

**Comment by zenith391** [comment]
This should now be fixed. Can you try it and tell me if it works?

**Comment by nazarii-muliak** [comment]
> This should now be fixed. Can you try it and tell me if it works?

Thanks a lot, it`s working now

**Comment by IdolonInMachina** [comment]
Just a heads up, this seems to be occuring again - looks like the artifact has expired.
