### ISSUE TITLE
Launching multiple instances with different filesystems?

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [zenith391/OCEmu#7]
I'd like to launch multiple instances of OCEmu, each with different UUIDs for components and separate filesystems, able to communicate via `component.modem`. Is this achieveable in the current state of OCEmu?

**Comment by misiuji** [comment]
Right now I don't think so but maybe through some command line arguments or something similar in the future. I'm gonna look into it tomorrow

**Comment by JohnTheCoolingFan** [comment]
I want to explain what I'm trying to achieve.
I want to use OCEmu as a tool for developing complex programs for opencomputers. In complex, I mean multiple computers that can communicate between each other using different networks. It makes development much easier when you have such an emulator.

**Comment by misiuji** [comment]
Sorry for my absens, I was busy with school. There is a system to allow the type of thing you are trying to do, but the addreses of the components are hard coded in the _ocemu.cfg_ file. This creates a conflict visible here:
![image](https://user-images.githubusercontent.com/46192406/104811005-e460ff00-57f8-11eb-9fef-c99233d1f655.png)
There is a way to asign a random address to a comopnent if it isn't specified. I'll experiment with that and tell you if I find anything.

**Comment by misiuji** [comment]
Soooo it is posible right now, but it is really weird.
![image](https://user-images.githubusercontent.com/46192406/104811408-9dc0d400-57fb-11eb-883f-5547682a9e21.png)
the first message is from this computer and the secound is from a different one in another window.

the way OCEmu asigns addresses is qiute simple:
1. load components from _ocemu.cfg_. It's in a table like this:
![image](https://user-images.githubusercontent.com/46192406/104811507-440cd980-57fc-11eb-9085-725cf626c7fc.png)
2. (for each component) if the secound value is a string, asing it to the address, else generate a new random one
3. save the current config to _ocemu.cfg_

so to get the two computers with different modem adderess right now you need to:
1. launch the first computer like normal
2. change the modem address to something other then a string in _ocemu.cfg_ like this: 
![image](https://user-images.githubusercontent.com/46192406/104811589-f17fed00-57fc-11eb-8213-3ca8c7766478.png)
3. launch the other computer, it shoud update the _ocemu.cfg_ to it's own config
the computers are now able to communicate with each other, but they sill have the same file system.

I'll try to make this a little simpler, any suggestions?

**Comment by JohnTheCoolingFan** [comment]
Wow! That's awesome!
It's a little bit inconvenient, but I think that's a good start. I suggest that there would be a way to make different configurations of components and tell OCEmu to launch using these components.
And also, what do parameters for modem component mean? Is there a way to set to which network it is connected?

**Comment by misiuji** [comment]
Do you mind talking on discord? I have a few thing that I want to talk about a bit. Here's my tag: misiuji#6487

**Comment by misiuji** [comment]
So we got this:
a list of component configurations for different computers identified with names 
they would be stored in a table in _ocemu.cfg_ and could be choosen with a command line agument
there would be a command line tool for configuring them as well
what do you think @zenith391?

**Comment by zenith391** [comment]
This could be implemented as a command-line option to select a custom `ocemu.cfg`, so you can launch a first instance in command line with (on Linux)
```sh
lua boot.lua --config first_computer.cfg
```
and a second window with
```sh
lua boot.lua --config second_computer.cfg
```

This way the difference between the two computers can be more than just components (by example, one is running fast mode and the other isn't)

**Comment by misiuji** [comment]
That's how it could work, with the tools i've mentioned for front end
like a choose your components kinda deal

**Comment by misiuji** [comment]
How about switching to [this](https://github.com/mpeterv/argparse) argument parser?

**Comment by misiuji** [comment]
So i just learnt that you can already do this. You just specify the dir of the machine folder after OCEmu.exe or lua boot.lua

**Comment by misiuji** [comment]
@zenith391 this can be closed now
