### ISSUE TITLE
Can't find ocemu.cfg

### ISSUE THREAD

**Issue by devclyde** [zenith391/OCEmu#8]
I use Manjaro, I did all the installation procedures, but at the time run `lua boot.lua`, he sends an error saying he did not find the file `ocemu.cfg`:

![image](https://user-images.githubusercontent.com/49321124/106185894-3fdca680-6182-11eb-8528-2cbfdb85e8fd.png)

How fix this?

**Comment by misiuji** [comment]
The issue is not that there is no config, it will use the default one. 
What version of lua are you using?

**Comment by zenith391** [comment]
The bug was caused by `bit32` not being available in Lua 5.3
